import type {
  Adr,
  ApiEndpoint,
  ApiSpec,
  Diagram,
  DiagramVersion,
  ProjectSummary,
  ServiceSelection,
  ServiceCatalogItem,
  AiReview,
} from "./types";
import type { CostBreakdown } from "./cost";
import { DIAGRAM_KIND_MAP, METHOD_RAW_STYLE, SERVICE_CATEGORY_MAP, AUTH_TYPES } from "./constants";
import { formatCurrency, formatDate, formatDateTime } from "./utils";
import type { GraphNode, GraphEdge } from "./analysis";

/* ------------------------------------------------------------------ */
/*  Small markdown helpers                                            */
/* ------------------------------------------------------------------ */

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) return "_No rows._\n";
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map((c) => c.replace(/\|/g, "\\|")).join(" | ")} |`);
  return [head, sep, ...body].join("\n");
}

function safe(text: string | null | undefined, fallback = "\u2014"): string {
  return text && text.trim() ? text.trim() : fallback;
}

/* ------------------------------------------------------------------ */
/*  Architecture document                                             */
/* ------------------------------------------------------------------ */

export interface ArchitectureDocInput {
  project: ProjectSummary;
  diagrams: Diagram[];
  versions: Record<string, DiagramVersion | null>;
  adrs: Adr[];
  selections: ServiceSelection[];
  catalogById: Map<string, ServiceCatalogItem>;
  cost: CostBreakdown;
  latestReview: AiReview | null;
}

function graphFromVersion(version: DiagramVersion): { nodes: GraphNode[]; edges: GraphEdge[] } {
  const nodes = (version.nodes ?? []) as unknown as Array<{
    id: string;
    data?: Record<string, unknown>;
    position?: { x: number; y: number };
  }>;
  const edges = (version.edges ?? []) as unknown as Array<{
    id: string;
    source: string;
    target: string;
    data?: Record<string, unknown>;
  }>;

  return {
    nodes: nodes.map((n) => ({
      id: n.id,
      label: (n.data?.label as string) || n.id,
      kind: (n.data?.kind as string) || "service",
      layer: (n.data?.layer as string) || "application",
      technology: n.data?.technology as string | undefined,
      description: n.data?.description as string | undefined,
      responsibility: n.data?.responsibility as string | undefined,
      criticality: n.data?.criticality as string | undefined,
      replication: n.data?.replication as string | undefined,
      notes: n.data?.notes as string | undefined,
      position: n.position,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      protocol: e.data?.protocol as string | undefined,
      direction: (e.data?.direction as string) || "sync",
      description: e.data?.description as string | undefined,
      auth: e.data?.auth as string | undefined,
      sla: e.data?.sla as string | undefined,
      label: e.data?.label as string | undefined,
    })),
  };
}

export function generateArchitectureDoc({
  project,
  diagrams,
  versions,
  adrs,
  selections,
  cost,
  latestReview,
}: ArchitectureDocInput): string {
  const out: string[] = [];
  const ctx = project.context ?? {};

  out.push(`# ${project.name} \u2014 Architecture Documentation`);
  out.push(``);
  out.push(`> Generated by AI System Architect on ${formatDate(new Date().toISOString())}`);
  out.push(``);
  out.push(
    table(
      ["Field", "Value"],
      [
        ["Status", project.status],
        ["Owner role in project", safe(project.my_role)],
        ["Last updated", formatDateTime(project.updated_at)],
        ["Diagrams", String(diagrams.length)],
        ["Decisions recorded", String(adrs.length)],
        ["Estimated monthly cost", formatCurrency(cost.monthlyTotal)],
      ],
    ),
  );
  out.push(``);

  if (ctx.goal || ctx.scope) {
    out.push(`## 1. System context`);
    out.push(``);
    if (ctx.goal) {
      out.push(`**Goal.** ${ctx.goal}`);
      out.push(``);
    }
    if (ctx.scope) {
      out.push(`**Scope.** ${ctx.scope}`);
      out.push(``);
    }
    if (Array.isArray(ctx.users) && ctx.users.length > 0) {
      out.push(`**Users and actors.**`);
      out.push(``);
      for (const user of ctx.users as string[]) out.push(`- ${user}`);
      out.push(``);
    }
    if (Array.isArray(ctx.constraints) && ctx.constraints.length > 0) {
      out.push(`**Constraints.**`);
      out.push(``);
      for (const c of ctx.constraints as string[]) out.push(`- ${c}`);
      out.push(``);
    }
  }

  out.push(`## 2. Diagrams`);
  out.push(`>`);
  out.push(`> Visual diagrams are stored in the platform. This document describes every component`);
  out.push(`> and connection captured in the latest saved version of each diagram.`);
  out.push(``);

  if (diagrams.length === 0) {
    out.push(`No diagrams have been created yet.`);
    out.push(``);
  }

  let section = 3;
  for (const diagram of diagrams) {
    const version = versions[diagram.id];
    out.push(`### 2.${section - 2} ${diagram.name}`);
    out.push(``);
    out.push(
      `*${DIAGRAM_KIND_MAP[diagram.kind] ?? diagram.kind} \u2014 version ${diagram.current_version} \u2014 last saved ${formatDateTime(diagram.updated_at)}*`,
    );
    out.push(``);
    if (diagram.description) {
      out.push(diagram.description);
      out.push(``);
    }
    if (version?.notes) {
      out.push(`> ${version.notes}`);
      out.push(``);
    }

    if (!version) {
      out.push(`_This diagram has no saved version yet._`);
      out.push(``);
      section += 1;
      continue;
    }

    const { nodes, edges } = graphFromVersion(version);

    if (nodes.length === 0) {
      out.push(`_This diagram is empty._`);
      out.push(``);
      section += 1;
      continue;
    }

    out.push(`#### Components (${nodes.length})`);
    out.push(``);
    out.push(
      table(
        ["Component", "Layer", "Type", "Technology", "Responsibility", "Criticality"],
        nodes.map((n) => [
          n.label,
          n.layer,
          n.kind,
          safe(n.technology),
          safe(n.responsibility ?? n.description),
          safe(n.criticality),
        ]),
      ),
    );
    out.push(``);

    out.push(`#### Connections (${edges.length})`);
    out.push(``);
    out.push(
      table(
        ["From", "To", "Protocol", "Mode", "Auth", "SLA"],
        edges.map((e) => {
          const from = nodes.find((n) => n.id === e.source)?.label ?? e.source;
          const to = nodes.find((n) => n.id === e.target)?.label ?? e.target;
          return [from, to, safe(e.protocol), e.direction ?? "sync", safe(e.auth, "none"), safe(e.sla, "none")];
        }),
      ),
    );
    out.push(``);

    const withReplication = nodes.filter((n) => n.replication?.trim());
    if (withReplication.length > 0) {
      out.push(`#### Replication & resilience`);
      out.push(``);
      for (const n of withReplication) out.push(`- **${n.label}** \u2014 ${n.replication}`);
      out.push(``);
    }

    section += 1;
  }

  out.push(`## ${section}. Architecture decisions`);
  out.push(``);
  if (adrs.length === 0) {
    out.push(`No architecture decision records have been created.`);
    out.push(``);
  } else {
    out.push(
      table(
        ["#", "Decision", "Status", "Date"],
        adrs
          .slice()
          .sort((a, b) => a.number - b.number)
          .map((a) => [`ADR-${String(a.number).padStart(3, "0")}`, safe(a.title), a.status, formatDate(a.created_at)]),
      ),
    );
    out.push(``);
    for (const adr of adrs.slice().sort((a, b) => a.number - b.number)) {
      out.push(`### ADR-${String(adr.number).padStart(3, "0")}: ${adr.title}`);
      out.push(``);
      out.push(`**Status:** ${adr.status}`);
      out.push(``);
      if (adr.context) {
        out.push(`**Context**`);
        out.push(``);
        out.push(adr.context);
        out.push(``);
      }
      if (adr.decision) {
        out.push(`**Decision**`);
        out.push(``);
        out.push(adr.decision);
        out.push(``);
      }
      if (adr.consequences) {
        out.push(`**Consequences**`);
        out.push(``);
        out.push(adr.consequences);
        out.push(``);
      }
      if (adr.alternatives) {
        out.push(`**Alternatives considered**`);
        out.push(``);
        out.push(adr.alternatives);
        out.push(``);
      }
    }
  }

  section += 1;
  out.push(`## ${section}. Technology stack and cost`);
  out.push(``);
  if (selections.length === 0) {
    out.push(`No services have been selected for this project.`);
    out.push(``);
  } else {
    out.push(
      table(
        ["Service", "Vendor", "Category", "Qty", "Unit", "Unit price", "Monthly"],
        cost.lines.map((l) => [
          l.name,
          safe(l.vendor),
          SERVICE_CATEGORY_MAP[l.category as keyof typeof SERVICE_CATEGORY_MAP] ?? l.category,
          String(l.quantity),
          l.unit,
          formatCurrency(l.unitPrice),
          formatCurrency(l.monthly),
        ]),
      ),
    );
    out.push(``);
    out.push(`**Total:** ${formatCurrency(cost.monthlyTotal)}/month \u00b7 ${formatCurrency(cost.annualTotal)}/year`);
    out.push(``);
    if (cost.assumptions.length > 0) {
      out.push(`**Assumptions**`);
      out.push(``);
      for (const a of cost.assumptions) out.push(`- ${a}`);
      out.push(``);
    }
  }

  section += 1;
  out.push(`## ${section}. Review findings`);
  out.push(``);
  if (!latestReview) {
    out.push(`No architecture review has been run for this project.`);
    out.push(``);
  } else {
    out.push(
      `Latest review: **${latestReview.score}/100** (${latestReview.engine}${
        latestReview.model ? ` / ${latestReview.model}` : ""
      }) on ${formatDateTime(latestReview.created_at)}`,
    );
    out.push(``);
    out.push(latestReview.summary);
    out.push(``);
    for (const f of latestReview.findings ?? []) {
      out.push(`- **[${f.severity.toUpperCase()}] ${f.title}** (${f.category}) \u2014 ${f.detail}`);
      if (f.suggestion) out.push(`  - _Suggestion:_ ${f.suggestion}`);
    }
    out.push(``);
  }

  out.push(`---`);
  out.push(``);
  out.push(
    `_Generated by AI System Architect. Diagram images are not embedded; open the project to view them._`,
  );

  return out.join("\n");
}

/* ------------------------------------------------------------------ */
/*  API document                                                      */
/* ------------------------------------------------------------------ */

export function generateApiDoc(spec: ApiSpec, endpoints: ApiEndpoint[]): string {
  const out: string[] = [];
  const groups = new Map<string, ApiEndpoint[]>();
  for (const e of endpoints) {
    groups.set(e.group_name || "default", [...(groups.get(e.group_name || "default") ?? []), e]);
  }

  out.push(`# ${spec.name} \u2014 API Reference`);
  out.push(``);
  out.push(`> Generated by AI System Architect on ${formatDate(new Date().toISOString())}`);
  out.push(``);
  if (spec.description) {
    out.push(spec.description);
    out.push(``);
  }
  out.push(
    table(
      ["Field", "Value"],
      [
        ["Version", spec.version],
        ["Base URL", spec.base_url],
        ["Endpoints", String(endpoints.length)],
        ["Authentication", [...new Set(endpoints.map((e) => e.auth_type))].join(", ") || "none"],
      ],
    ),
  );
  out.push(``);
  out.push(`## Endpoint summary`);
  out.push(``);
  out.push(
    table(
      ["Method", "Path", "Group", "Auth", "Summary"],
      endpoints.map((e) => [
        e.method.toUpperCase(),
        `\`${e.path}\``,
        safe(e.group_name),
        AUTH_TYPES.find((a) => a.id === e.auth_type)?.label ?? e.auth_type,
        safe(e.summary),
      ]),
    ),
  );
  out.push(``);

  out.push(`## Endpoints`);
  out.push(``);
  for (const [group, groupEndpoints] of groups) {
    out.push(`### ${group}`);
    out.push(``);
    for (const e of groupEndpoints) {
      out.push(`#### \`${e.method.toUpperCase()} ${e.path}\``);
      out.push(``);
      if (e.is_deprecated) {
        out.push(`> **Deprecated.**`);
        out.push(``);
      }
      if (e.summary) {
        out.push(e.summary);
        out.push(``);
      }
      if (e.description) {
        out.push(e.description);
        out.push(``);
      }
      out.push(
        table(
          ["Property", "Value"],
          [
            ["Operation ID", safe(e.operation_id)],
            ["Auth", AUTH_TYPES.find((a) => a.id === e.auth_type)?.label ?? e.auth_type],
            ["Rate limit", safe(e.rate_limit)],
            ["Tags", (e.tags ?? []).join(", ") || "\u2014"],
          ],
        ),
      );
      out.push(``);

      if ((e.params ?? []).length > 0) {
        out.push(`**Parameters**`);
        out.push(``);
        out.push(
          table(
            ["Name", "In", "Type", "Required", "Description"],
            e.params.map((p) => [p.name, p.in, p.type, p.required ? "yes" : "no", safe(p.description, "")]),
          ),
        );
        out.push(``);
      }

      if (e.request_body) {
        out.push(`**Request body**`);
        out.push(``);
        out.push("```json");
        out.push(JSON.stringify(e.request_body, null, 2));
        out.push("```");
        out.push(``);
      }

      out.push(`**Responses**`);
      out.push(``);
      const responseEntries = Object.entries(e.responses ?? {});
      if (responseEntries.length === 0) {
        out.push(`_No responses defined._`);
      } else {
        out.push(
          table(
            ["Status", "Description"],
            responseEntries.map(([status, value]) => [
              status,
              safe((value as Record<string, unknown>)?.description as string),
            ]),
          ),
        );
      }
      out.push(``);

      if ((e.errors ?? []).length > 0) {
        out.push(`**Errors**`);
        out.push(``);
        out.push(
          table(
            ["HTTP", "Code", "Description"],
            e.errors.map((err) => [String(err.httpStatus), err.code, err.description]),
          ),
        );
        out.push(``);
      }

      out.push(
        `\`\`\`bash\ncurl -X ${e.method.toUpperCase()} '${spec.base_url.replace(/\/$/, "")}${e.path}' \\\n  -H 'Accept: application/json'\n\`\`\``,
      );
      out.push(``);
    }
  }

  return out.join("\n");
}

/* ------------------------------------------------------------------ */
/*  Cost report                                                       */
/* ------------------------------------------------------------------ */

export function generateCostDoc(
  project: ProjectSummary,
  cost: CostBreakdown,
  insights: string[],
): string {
  const out: string[] = [];
  out.push(`# ${project.name} \u2014 Infrastructure Cost Model`);
  out.push(``);
  out.push(`> Generated by AI System Architect on ${formatDate(new Date().toISOString())}`);
  out.push(``);

  out.push(`## Summary`);
  out.push(``);
  out.push(
    table(
      ["Metric", "Value"],
      [
        ["Monthly run rate", formatCurrency(cost.monthlyTotal)],
        ["Annual projection", formatCurrency(cost.annualTotal)],
        ["Services tracked", String(cost.lines.length)],
        ["Distinct categories", String(cost.byCategory.length)],
      ],
    ),
  );
  out.push(``);

  out.push(`## Cost by category`);
  out.push(``);
  out.push(
    table(
      ["Category", "Monthly", "Share"],
      cost.byCategory.map((c) => [
        SERVICE_CATEGORY_MAP[c.category as keyof typeof SERVICE_CATEGORY_MAP] ?? c.category,
        formatCurrency(c.monthly),
        `${c.share.toFixed(1)}%`,
      ]),
    ),
  );
  out.push(``);

  out.push(`## Line items`);
  out.push(``);
  out.push(
    table(
      ["Service", "Vendor", "Qty", "Unit", "Unit price", "Monthly", "Annual"],
      cost.lines.map((l) => [
        l.name,
        safe(l.vendor),
        String(l.quantity),
        l.unit,
        formatCurrency(l.unitPrice),
        formatCurrency(l.monthly),
        formatCurrency(l.annual),
      ]),
    ),
  );
  out.push(``);

  if (cost.assumptions.length > 0) {
    out.push(`## Assumptions`);
    out.push(``);
    for (const a of cost.assumptions) out.push(`- ${a}`);
    out.push(``);
  }

  if (insights.length > 0) {
    out.push(`## Observations`);
    out.push(``);
    for (const i of insights) out.push(`- ${i}`);
    out.push(``);
  }

  out.push(`---`);
  out.push(``);
  out.push(
    `_Estimates exclude taxes, support plans, committed-use discounts and egress overages. Validate against your provider's calculator before budgeting._`,
  );

  return out.join("\n");
}

/* ------------------------------------------------------------------ */
/*  ADR bundle                                                        */
/* ------------------------------------------------------------------ */

export function generateAdrDoc(project: ProjectSummary, adrs: Adr[]): string {
  const out: string[] = [];
  out.push(`# ${project.name} \u2014 Architecture Decision Records`);
  out.push(``);
  out.push(`> Generated by AI System Architect on ${formatDate(new Date().toISOString())}`);
  out.push(``);

  if (adrs.length === 0) {
    out.push(`No decision records have been created yet.`);
    return out.join("\n");
  }

  out.push(
    table(
      ["ID", "Title", "Status", "Tags", "Date"],
      adrs
        .slice()
        .sort((a, b) => a.number - b.number)
        .map((a) => [
          `ADR-${String(a.number).padStart(3, "0")}`,
          a.title,
          a.status,
          (a.tags ?? []).join(", ") || "\u2014",
          formatDate(a.created_at),
        ]),
    ),
  );
  out.push(``);
  out.push(`---`);
  out.push(``);

  for (const adr of adrs.slice().sort((a, b) => a.number - b.number)) {
    out.push(`## ADR-${String(adr.number).padStart(3, "0")}: ${adr.title}`);
    out.push(``);
    out.push(`- **Status:** ${adr.status}`);
    out.push(`- **Date:** ${formatDate(adr.created_at)}`);
    if ((adr.tags ?? []).length > 0) out.push(`- **Tags:** ${adr.tags.join(", ")}`);
    out.push(``);
    out.push(`### Context`);
    out.push(``);
    out.push(safe(adr.context, "_Not recorded._"));
    out.push(``);
    out.push(`### Decision`);
    out.push(``);
    out.push(safe(adr.decision, "_Not recorded._"));
    out.push(``);
    out.push(`### Consequences`);
    out.push(``);
    out.push(safe(adr.consequences, "_Not recorded._"));
    out.push(``);
    out.push(`### Alternatives considered`);
    out.push(``);
    out.push(safe(adr.alternatives, "_Not recorded._"));
    out.push(`---`);
    out.push(``);
  }

  return out.join("\n");
}

/* ------------------------------------------------------------------ */
/*  Mermaid diagram (embeddable in Markdown)                           */
/* ------------------------------------------------------------------ */

function mermaidId(label: string, index: number): string {
  return `n${index}_${label.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 24)}`;
}

export function generateMermaid(diagram: Diagram, version: DiagramVersion): string {
  const { nodes, edges } = graphFromVersion(version);
  if (nodes.length === 0) return "```mermaid\ngraph TD\n  empty[No components yet]\n```\n";

  const lines: string[] = ["```mermaid", "graph LR"];

  nodes.forEach((node, i) => {
    const id = mermaidId(node.label, i);
    const label = node.label.replace(/"/g, "'").replace(/[\[\]()]/g, "");
    lines.push(`  ${id}["${label}"]`);
  });

  for (const edge of edges) {
    const si = nodes.findIndex((n) => n.id === edge.source);
    const ti = nodes.findIndex((n) => n.id === edge.target);
    if (si < 0 || ti < 0) continue;
    const from = mermaidId(nodes[si].label, si);
    const to = mermaidId(nodes[ti].label, ti);
    const arrow = edge.direction === "async" || edge.direction === "batch" ? "-.->" : "-->";
    const tag = [edge.protocol, edge.direction].filter(Boolean).join(" ");
    lines.push(`  ${from} ${arrow}|"${tag}"| ${to}`);
  }

  lines.push("```");
  return lines.join("\n");
}

export { METHOD_RAW_STYLE, catalogHelper };

function catalogHelper(map: Map<string, ServiceCatalogItem>) {
  return (id: string) => map.get(id)?.name ?? id;
}
